### ISSUE TITLE
v1.2.0 is not available on grafana labs plugins store

### ISSUE THREAD

**Issue by vermaabhay** [digrich/bubblechart-panel#11]
Hi @digrich,

Version 1.2.0 of bubblechart-panel is not published on grafana labs plugin store. Also, just wanted to understand if we are signing this plugin as grafana is now verifying the identity of each plugin.

**Comment by digrich** [comment]
I have published the latest version of plugin and waiting for the grafana team to verify it. And I am not sure if grafana is enforcing the signature at this point for community plugins.

**Comment by digrich** [comment]
v1.2.0 is available on grafana plugin store.
