### ISSUE TITLE
Error: <circle> attribute r: Expected length, "NaN" (with Grafana v7.0.6)

### ISSUE THREAD

**Issue by nguyenlamlll** [digrich/bubblechart-panel#13]
Hi digrich, first of all, thank you very much for your plugin!

 I just want to submit and log an issue I have encountered a few times when using this plugin.

Sometimes, when you load the graphs, a bubble chart will fail to display, appearing like the picture below. We can also see that it does not happen to all of them. The next one is still rendering normally.

![image](https://user-images.githubusercontent.com/20963684/94988229-e7abe400-0595-11eb-8421-3c20b557eae6.png)

When opening the console log, the error is

```
d3.v3.min.js:1 Error: <circle> attribute r: Expected length, "NaN".
```

Moreover, if this info helps, with that chart, I'm using TestDB data source of Grafana. 

Anyways, I might clone the repo and debug this later when I'm available.

**Comment by digrich** [comment]
@nguyenlamlll - This usually happen when all values are zero. Is that the case here?

**Comment by nguyenlamlll** [comment]
Hi, I don't think that's the case. I see that it seems to only happen when I use the TestDB data source (even with the settings so the values never reach 0).

**Comment by digrich** [comment]
@nguyenlamlll  - Can you please check with the latest version of plugin?
