### ISSUE TITLE
MySQL datasource not working with Grafana 8

### ISSUE THREAD

**Issue by biohazardxxx** [digrich/bubblechart-panel#15]
With Grafana 8 there has been a change on the data format for MS SQL and MySQL. The Plugin does not show anything after upgrade. With Influx it works fine.
Please see a similar issue at anohter panel:
https://github.com/grafana/worldmap-panel/pull/318

**Comment by ryantxu** [comment]
This transformer should help:
https://github.com/grafana/grafana/pull/36737

**Comment by biohazardxxx** [comment]
Indeed! After upgrading to 8.0.6 and setting the transfomer like below it works. Thanks!
![image](https://user-images.githubusercontent.com/1370362/126306326-a41d8629-7ce7-454e-94c1-d796c725e986.png)

**Comment by digrich** [comment]
Hi @biohazardxxx - I hope using the transformer would have resolved your issue. Please let me know if you get any further issues.
