### ISSUE TITLE
Panel not show on dashboard screen

### ISSUE THREAD

**Issue by NovakIvgeny** [digrich/bubblechart-panel#17]
Hi digrich,

Thank you for that panel, I just have a minor issue that I don't see the panel information on the main dashboard screen, when i edit the panel its like that:
![image](https://user-images.githubusercontent.com/98711035/191309883-d2f631ee-abc4-4125-9034-10aa71500d31.png)

but when i save and look at the main dashboard its empty:
![image](https://user-images.githubusercontent.com/98711035/191310049-2c088d08-f69a-446f-8b6c-e12cf2679697.png)

Thank you in advance for you help!

**Comment by digrich** [comment]
Hi @NovakIvgeny - A recently released React-based new version is available; can you please use that and let me know if the issue still exists.
