### ISSUE TITLE
Label artifact left behind on refresh

### ISSUE THREAD

**Issue by gibsonc** [digrich/bubblechart-panel#2]
Grafana 4.4.3
Bubblechart 1.0.0
Chrome 61 and IE 11 tested

To reproduce, start with a fresh graph.
Hover over a bubble - the label appears with the value.
Let the graph auto refresh while hovering and after refresh, move the mouse to another bubble. 
The first label remains and a new label appears for the new selected bubble.

In addition, going to another dashboard still leaves the artifact behind.

**Comment by digrich** [comment]
Thanks, @gibsonc for reporting the issue. I will try to fix this in next release.
