### ISSUE TITLE
where is the release of 1.1.0?

### ISSUE THREAD

**Issue by biohazardxxx** [digrich/bubblechart-panel#5]
Hi,

in the readme.md it is written version 1.1.0 is out but it was not released on the Grafana plugin page:
https://grafana.com/plugins/digrich-bubblechart-panel/installation
neither here on git hub.

I know it is just a matter of downloading the code as zip here but new users would get the old version via the plugin page.

**Comment by digrich** [comment]
Thanks for reporting. I am working with Grafana team to resolve this.

**Comment by digrich** [comment]
This has been resolved now.
