### ISSUE TITLE
Does not resize anymore

### ISSUE THREAD

**Issue by biohazardxxx** [digrich/bubblechart-panel#6]
With version 1.1.0 the whole buble chart does not resize. Set the height to 800 but still empty space is not used. It is hardly possible to ready anything in the bubbles.
THis was working with previous version.
![image](https://user-images.githubusercontent.com/1370362/36467582-9f9e4f9c-16df-11e8-9290-7d7e7a13450f.png)

It would be great if you would have a quick fix (to manual edit a file or so) since like this the chart is not usable.

**Comment by digrich** [comment]
Which grafana version, you are using? Did you try with 5.0.0-beta release?

**Comment by biohazardxxx** [comment]
It is Grafana v4.6.1
Did not try with 5 beta since this install is used daily.

**Comment by digrich** [comment]
@biohazardxxx Try with latest changes.

**Comment by biohazardxxx** [comment]
Works! Many thanks!
