### ISSUE TITLE
Rendering incorrect if all values are zero

### ISSUE THREAD

**Issue by svdasein** [digrich/bubblechart-panel#8]
If one attempts to graph a set of values wherein all values are zero (0), the panel renders very strangely.  If text is enabled one sees all text jumbled together in one big glob, and with text disabled ones sees what appears to be a single pixel.

I have been able to work around this by setting an offset of +1 to all values.  Once I do that the panel renders properly even when all values are in reality zero.

**Comment by svdasein** [comment]
With no offset, all values zero:
![snapshot6](https://user-images.githubusercontent.com/511777/56829103-74426680-6828-11e9-88f0-e96173c6c47c.png)

With offset +1:

![snapshot6](https://user-images.githubusercontent.com/511777/56829157-9cca6080-6828-11e9-9e2c-609613cb70aa.png)

**Comment by biohazardxxx** [comment]
+1

**Comment by digrich** [comment]
@svdasein - It has been fixed in the new version of the plugin. Please check and let me know if you encounter any issues.
